apiVersion: v1
kind: Service
metadata:
  name: nombre-del-servicio
spec:
  selector:
    app: nombre-de-la-imagen
  ports:
    - protocol: TCP
      port: 80  # Puerto del servicio
      targetPort: 8080  # Puerto de tu aplicación
  type: NodePort
